return {
    {
        name="name",
        type="string",
    },
    {
        name="enabled",
        type="boolean",
    },
    {
        name="interactable",
        type="boolean",
    },
    {
        name="scrollable",
        type="boolean",
    },
    {
        name="hide_cursor_interaction",
        type="boolean",
    },
    {
        name="parent",
        type="Actor",
        required=false,
        include_partial=false,
    },
    {
        name="early_update",
        type="method",
    },
    {
        name="update",
        type="method",
    },
    {
        name="late_update",
        type="method",
    },
    {
        name="init",
        type="method",
    },
    {
        name="on_hover",
        type="method",
    },
    {
        name="on_un_hover",
        type="method",
    },
    {
        name="on_click",
        type="method",
    },
    {
        name="on_click_release",
        type="method",
    },
    {
        name="on_scroll",
        type="method",
    },
}