return {
    {
        name="color",
        type="Color",
    },
    {
        name="hovered_color",
        type="Color",
    },
    {
        name="clicked_color",
        type="Color",
    },
    {
        name="transparency",
        type="number",
    },
    {
        name="texture",
        type="Texture",
    },
    {
        name="uv_offset",
        type="Vec2",
    },
    {
        name="uv_scale",
        type="Vec2",
    },
    {
        name="material",
        type="Material",
    },
    {
        name="mesh",
        type="Mesh",
    },
}