return {
    {
        name="background_color",
        type="Color",
    },
    {
        name="background_hovered_color",
        type="Color",
    },
    {
        name="background_clicked_color",
        type="Color",
    },
    {
        name="background_transparency",
        type="number",
    },
    {
        name="background_texture",
        type="Texture",
        include_partial=false,
    },
    {
        name="background_texture",
        type="Texture | string",
        include_actor=false,
    },
    {
        name="background_uv_offset",
        type="Vec2",
    },
    {
        name="background_uv_scale",
        type="Vec2",
    },
    {
        name="background_material",
        type="Material",
    },
}