return {
    {
        name="slice_bottom",
        type="number",
    },
    {
        name="slice_top",
        type="number",
    },
    {
        name="slice_left",
        type="number",
    },
    {
        name="slice_right",
        type="number",
    },
    {
        name="size_bottom",
        type="UDim",
    },
    {
        name="size_top",
        type="UDim",
    },
    {
        name="size_left",
        type="UDim",
    },
    {
        name="size_right",
        type="UDim",
    },
    {
        name="axis_stretch_x",
        type="AxisStretchMode",
    },
    {
        name="axis_stretch_y",
        type="AxisStretchMode",
    },
    {
        name="side_overflow_behavior",
        type="SideOverflowBehavior",
    },
}