return {
    {
        name="text",
        type="string",
    },
    {
        name="text_color",
        type="Color",
    },
    {
        name="emoji_color",
        type="Color",
    },
    {
        name="caret_color",
        type="Color",
    },
    {
        name="text_material",
        type="Material",
    },
    {
        name="emoji_material",
        type="Material",
    },
    {
        name="caret_material",
        type="Material",
    },
    {
        name="font_size",
        type="UDim",
    },
    {
        name="line_height_em",
        type="number",
    },
    {
        name="padding_top_em",
        type="number",
    },
    {
        name="padding_bottom_em",
        type="number",
    },
    {
        name="font_family",
        type="string",
    },
    {
        name="text_alignment",
        type="TextAlignment",
        required=false,
    },
    {
        name="text_scaling",
        type="TextScaling",
    },
    {
        name="text_wrap",
        type="TextWrap",
    },
    {
        name="text_weight",
        type="TextWeight",
    },
    {
        name="text_stretch",
        type="TextStretch",
    },
    {
        name="editable",
        type="boolean",
    },
}