return {
    {
        name="position",
        type="UDim2",
    },
    {
        name="scale",
        type="UDim2",
    },
    {
        name="anchor",
        type="Vec2",
    },
    {
        name="rotation",
        type="number",
    },
    {
        name="snap_to_pixels",
        type="boolean",
    },
    {
        name="put_center",
        type="method",
        include_partial=false,
    },
    {
        name="push_left",
        type="method",
        include_partial=false,
    },
    {
        name="push_right",
        type="method",
        include_partial=false,
    },
    {
        name="push_top",
        type="method",
        include_partial=false,
    },
    {
        name="push_bottom",
        type="method",
        include_partial=false,
    },
}