return {
    {
        name="camera",
        type="Camera2D",
        include_partial=false
    },
    {
        name="render_texture",
        type="Texture",
        include_partial=false
    },
    {
        name="resolution_mult",
        type="number",
    },
    {
        name="rerender_count",
        type="number",
    },
    {
        name="texture_format",
        type="TextureFormat",
    },
    {
        name="double_buffer",
        type="boolean",
    },
    {
        name="view_color",
        type="Color",
    },
    {
        name="view_hovered_color",
        type="Color",
    },
    {
        name="view_clicked_color",
        type="Color",
    },
    {
        name="view_transparency",
        type="number",
    },
    {
        name="view_uv_offset",
        type="Vec2",
    },
    {
        name="view_uv_scale",
        type="Vec2",
    },
    {
        name="view_material",
        type="Material",
    },
}